### ISSUE TITLE
Icon for dark theme

### ISSUE THREAD

**Issue by Reeywhaar** [Reeywhaar/want-my-rss#1]

**Comment by happysurf** [comment]
Yes, with my FirefoxColor dark theme is bad to see the icon, I suggest orange color.

![rss](https://user-images.githubusercontent.com/13637587/48832251-04abe500-ed79-11e8-92b7-713d9f7f54b6.png)

**Comment by Reeywhaar** [comment]
https://github.com/Mte90/Share-Backported/issues/15
https://stackoverflow.com/questions/48540523/firefox-pick-page-action-icon-for-dark-light-themes
https://discourse.mozilla.org/t/use-theme-colors-for-svg-favicons/29165/7

It really irritates that Mozilla doesn't provide any suitable way to select icon for theme, seems like API is very inconsistent in this part. They have a way for their own extensions, even have [Photon page](https://design.firefox.com/photon/visuals/color.html#icons-and-other-elements) dedicated to this, yet provide no way to actually set color.

The solutions for now is either use neutral (#999, which looks like bug in both themes, or orange as you suggested which distracts) color, or have an option to manually set icon color, which is over-complication for such simple thing.

**Comment by Reeywhaar** [comment]
I've recently updated icon, and now I hope it has better appearance.
![image](https://user-images.githubusercontent.com/884649/173258698-0969143e-b6c4-4550-b142-9cce8bad4ee0.png)
