### ISSUE TITLE
Add a 'copy to clipboard' botton

### ISSUE THREAD

**Issue by alexis26** [Reeywhaar/want-my-rss#12]
It would be really  very convenient to have a button 'add to clipboard' in the case of using external rss reader
![want my rss](https://user-images.githubusercontent.com/3404404/50404501-f7837b00-07a8-11e9-8fc0-b3e3195e5b81.png)
thank you

**Comment by Reeywhaar** [comment]
I'm closing this for now, but if I understood something wrong, let me know
