### ISSUE TITLE
More obvious marking of visited links?

### ISSUE THREAD

**Issue by jscher2000** [Reeywhaar/want-my-rss#13]
The color difference between unvisited and visited links is not as dramatic as the browser's default colors, so it could be tricky for some users to scan down and open only the pages they have not viewed before. Something to consider for the future as you start getting theming requests.

**Comment by Reeywhaar** [comment]
Oh, there is longstanding battle with design, I changed colors 4-5 times by this time already. I see unvisited as greenish blue, and visited as desaturated purple, so I distinguish them easily. There could be difference on your monitor though.

**Comment by Reeywhaar** [comment]
@jscher2000  I have increased the difference in new version
, let me know what you think.

![screen shot 2018-12-29 at 02 00 33](https://user-images.githubusercontent.com/884649/50530337-8d9f0480-0b0d-11e9-9b8b-d5918ba0e0aa.png)

**Comment by jscher2000** [comment]
Yes, that's helpful. The pale lavender-ish color is easier to recognize than the gray-ish color we had before.

![image](https://user-images.githubusercontent.com/8264646/50530731-6288c680-0ab5-11e9-91be-048142733893.png)

**Comment by Reeywhaar** [comment]
Thanks for the screenshots, I noticed that I broke to bottom link bar on the post :-)
