### ISSUE TITLE
Feature request: link to download podcast file?

### ISSUE THREAD

**Issue by sourcejedi** [Reeywhaar/want-my-rss#14]
My use for the old RSS support was to download podcasts.  I tried 0.10 of this extension, but I don't think it lets me do that.  I see an `<audio>` player for the podcast, but I can't see any way to download the podcast file (MP3).

Thanks for creating this extension, whether or not you implement my requested feature :-).

**Comment by Reeywhaar** [comment]
Thank you for this point, maybe I need to think of adding some link to media. But right now there is a standard way, you can right click on an audio element, and there will be context menu:
![screen shot 2018-12-28 at 23 16 30](https://user-images.githubusercontent.com/884649/50527066-eadb8b80-0af6-11e9-9800-c10357b6aea8.png)

**Comment by sourcejedi** [comment]
Oh!  Just like right clicking to save an image :-).  Thank you, that's really great to know.

**Comment by Reeywhaar** [comment]
Yeah, by the way, I have just updated extension, so now there is a link, near media
![screen shot 2018-12-29 at 01 53 36](https://user-images.githubusercontent.com/884649/50530257-c7234000-0b0c-11e9-8162-fa4ba24d563e.png)

**Comment by sourcejedi** [comment]
This is really nice, thanks again :-).
