### ISSUE TITLE
misses feed links?

### ISSUE THREAD

**Issue by atomGit** [Reeywhaar/want-my-rss#17]
ex: ghacks.net/category/firefox/
there's 3 feeds in the head that are not detected

**Comment by Reeywhaar** [comment]
So, about this. It seems that ghacks layout broken which results in every `<link rel="alternate">` to be outside `head` element. I dunno, notified them.
![screen shot 2019-01-09 at 11 02 31](https://user-images.githubusercontent.com/884649/50885386-a0171900-13fe-11e9-9e04-9af0a9875b7c.png)
