### ISSUE TITLE
Invalid Date

### ISSUE THREAD

**Issue by demiurge-ash** [Reeywhaar/want-my-rss#19]
All feeds show Invalid Date.
Example: http://feeds.reuters.com/news/artsculture

![rss1](https://user-images.githubusercontent.com/40300551/51084053-ed63f500-1734-11e9-94b2-ab418a83a7cf.gif)

![rss2](https://user-images.githubusercontent.com/40300551/51084052-ed63f500-1734-11e9-82ba-f9fcafa12f31.gif)

**Comment by Reeywhaar** [comment]
Hmm, works for me, maybe some locale issue? Thanks for report. Can you tell me os name, firefox version, system locale, please?

![screenshot 2019-01-13 at 15 42 22](https://user-images.githubusercontent.com/884649/51085426-e72c4380-1749-11e9-8b02-8838e68a2264.png)

**Comment by HeikoAdams** [comment]
I've got the same issue with Firefox 64.0.2 on Manjaro linux 18.0.2 and german locale

> new Date("Fri, 11 Jan 2019 17:14:14 -0500")
> Date 2019-01-11T22:14:14.000Z

**Comment by demiurge-ash** [comment]
Windows 7, Firefox 64.0.2, russian

> new Date("Fri, 11 Jan 2019 17:14:14 -0500")
Date 2019-01-11T22:14:14.000Z

**Comment by Reeywhaar** [comment]
Thanks guys, I'll take a look asap!

**Comment by Reeywhaar** [comment]
Fixed in [0.14](https://github.com/Reeywhaar/want-my-rss/releases/tag/0.14), already available at AMO. Thanks again for report!
