### ISSUE TITLE
missed feed: podcast

### ISSUE THREAD

**Issue by atomGit** [Reeywhaar/want-my-rss#20]
[activistpost.com](https://www.activistpost.com/) - WMR detects 3 feeds, misses the 4th:

`https://www.activistpost.com/feed/podcast`

also if you would, let me know  if the [rules file idea](https://github.com/Reeywhaar/want-my-rss/issues/16#issuecomment-452432691) might be something you want to consider

thanks!

**Comment by Reeywhaar** [comment]
Same thing as with ghacks. Layout is broken by template engine or something. Podcast feed link is outside head:
![screenshot 2019-01-13 at 17 50 57](https://user-images.githubusercontent.com/884649/51086777-d389d880-175b-11e9-8db1-3a87af79a0c3.png)
