### ISSUE TITLE
Stale cache - https://audioboom.com/channels/4908905.rss

### ISSUE THREAD

**Issue by sourcejedi** [Reeywhaar/want-my-rss#22]
I seem to be getting stale cache on some feed.  I noticed it on this feed just now.  Pressing F5 fixed it.  I don't know how well Firefox builtin RSS used to work with this, because I didn't use any audioboom.com feed before.

Visiting it now (after F5, but not using F5), Firefox developer tools shows a HTTP 200 response with `Cache-Control: max-age=900, public`.  So I'm not sure what's going on :-(.  I will try to capture more information the next time I see it.

I searched the web, but couldn't find any results about other open-source software having a specific difficulty with audioboom.com.

**Comment by Reeywhaar** [comment]
Thanks for report, I've added additional no-cache headers, though what I've seen in network log, original request was sent with "Cache-Control: max-age=0". Hope it will resolve the problem.

**Comment by sourcejedi** [comment]
That sounds familiar. Thanks for having a look at this.

The next episode of this podcast has been posted now.  I was able to see it without refreshing, and I was still using want-my-rss version 0.14.  So I have no idea what the problem was.
