### ISSUE TITLE
Relative links

### ISSUE THREAD

**Issue by GammaC0de** [Reeywhaar/want-my-rss#29]
Hi,
Thank you for this WebExtension, it works great.

I have one issue though:
The base URL for relative links inside the RSS feed should be the RSS feed URL, not `moz-extension://6bc84008-a33c-4e78-833e-d6ae00ba21be` 

Regards

**Comment by Reeywhaar** [comment]
I'm not sure I follow. You mean, that if RSS content has link with relative urls, link will be broken? Do you have example of such feed?

**Comment by GammaC0de** [comment]
Here is an example:
https://github.com/Reeywhaar.atom

Try to press any link and see what happens..

**Comment by Reeywhaar** [comment]
Fixed. Thanks!

**Comment by GammaC0de** [comment]
Thank you 🎉
