### ISSUE TITLE
XML encoding is ignored [bug]

### ISSUE THREAD

**Issue by selivan** [Reeywhaar/want-my-rss#32]
If RSS feed has other encoding that utf-8, want-my-rss ignores it.

Example: https://lleo.me/dnevnik/rss.xml

```
<?xml version='1.0' encoding='windows-1251'?>

...
```

It is displayed like this:

![image](https://user-images.githubusercontent.com/1208989/69143338-c3f4c200-0ad9-11ea-9bbd-dc21743512ee.png)

**Comment by Reeywhaar** [comment]
Oh my God, not Kaganov!
