### ISSUE TITLE
100% CPU usage on some pages, no preview generated

### ISSUE THREAD

**Issue by woj-tek** [Reeywhaar/want-my-rss#38]
**Describe the bug**
Recently the extension, upon selecting a feed from dropdown, started freezing the browser (100% cpu, can't do anything and one has to force-close the browser

**To Reproduce**
1. Go to https://www.biobiochile.cl/
2. Click on want-my-rss icon in the addressbar and select detected feed
3. Browser freezes

**Expected behavior**
I should see a preview of the RSS feed

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Browser Firefox
 - Version 81.0.1 (64-bit)

**Comment by mogoh** [comment]
Maybe the same issue:
Parsing some documents causing huge amount of memory.
Example: https://web.dev/feed.xml

**Comment by Reeywhaar** [comment]
As for https://www.biobiochile.cl/ everything seems to be fine for me. Guess it depends on content. As for https://web.dev/feed.xml I surely can see that cpu starts to heat up. Hope I will take a look soon. Thanks!

**Comment by woj-tek** [comment]
From my part: In the end I opted only for a plugin that detects the feeds and give me the links without previews.

**Comment by Reeywhaar** [comment]
Yeah, I noticed that it must be that web.dev has heavy interactive content and has lot of entries in feed. Guess I should think of some kind lazy rendering.

**Comment by Reeywhaar** [comment]
Moved to #66
