### ISSUE TITLE
feature request : is it possible to fix the speed of all podcasts

### ISSUE THREAD

**Issue by Janaue** [Reeywhaar/want-my-rss#43]
I play the podcasts with speed 1.5x so I would like to know if it's possible ot have the feature of fixing this value for all podcasts on the page of the addon, ie this
moz-extension://a722144b-a46d-4408-9f43-7755c0ba77d0/show.html?url=XXXXXXXXXXXXXXXXXXXX.rss

**Comment by NESC1US** [comment]
no, that's not how this add-on works - there is no audio in reading xml file containing feed (that contains links to audio files).
feel free to close this if you want.

**Comment by Reeywhaar** [comment]
Guess as an additional feature it can be discussed, but no plans for now.
