### ISSUE TITLE
Release notes in the extension and at AMO

### ISSUE THREAD

**Issue by grahamperrin** [Reeywhaar/want-my-rss#47]
<https://addons.mozilla.org/en-US/firefox/addon/want-my-rss/versions/0.18/updateinfo/> was OK. 

I see <https://github.com/Reeywhaar/want-my-rss/compare/0.19...0.20> however: 

1. the extension lacks a **Release notes** tab
2. <https://addons.mozilla.org/en-US/firefox/addon/want-my-rss/versions/0.19/updateinfo/> and <https://addons.mozilla.org/en-US/firefox/addon/want-my-rss/versions/0.20/updateinfo/> are empty. 

![image](https://user-images.githubusercontent.com/192271/145662603-9dd3039a-5326-4f24-9eb5-a0125a0baccc.png)

**Comment by Reeywhaar** [comment]
Since 0.19 extension released with https://github.com/kewisch/action-web-ext github action. As of now web-ext provides to way to embed release notes, and so they are missing. When there is a way to apply notes in automated way, I will be glad to add it to automation.
