### ISSUE TITLE
"This listing is not intended for this platform. Browse add-ons for Firefox on desktop" at addons.mozilla.org

### ISSUE THREAD

**Issue by rokejulianlockhart** [Reeywhaar/want-my-rss#63]
https://addons.mozilla.org/en-US/android/addon/want-my-rss/

![See below.](https://user-images.githubusercontent.com/42837531/233806138-6465282d-cee2-4f8b-9eb7-3f6a9315a104.png)

> This listing is not intended for this platform. [Browse add-ons for Firefox on desktop](https://addons.mozilla.org/en-US/firefox/addon/want-my-rss/).

**Comment by richarson** [comment]
The desktop version is the linked one in the yellow box:

https://addons.mozilla.org/en-US/firefox/addon/want-my-rss/
