### ISSUE TITLE
"Subscribe to page" icon

### ISSUE THREAD

**Issue by Lyhtande** [Reeywhaar/want-my-rss#65]
The "Subscribe to page" icon appears as a dot in Firefox' address bar.

Screenshot: https://i.imgur.com/T7BoFOt.png

**Comment by WildCrow** [comment]
Confirmed on my end too, Win 10 + Latest Firefox (x64) 

![image](https://github.com/Reeywhaar/want-my-rss/assets/5311996/676a4336-a7ad-4b3e-a218-1e184d0b100f)

**Comment by brunob** [comment]
Fixed by https://github.com/Reeywhaar/want-my-rss/commit/733bb937d9145b26297893b636fd182fe056d4b4 thx @Reeywhaar => issue should be closed
