### ISSUE TITLE
No RSS intercepted

### ISSUE THREAD

**Issue by happysurf** [Reeywhaar/want-my-rss#7]
To http://www.freshremix.ru/ pages no RSS is show because I get this error:

**Error while parsing feed**
http://www.freshremix.ru/house/rss.xml

**Comment by Reeywhaar** [comment]
Feed is corrupted and is not valid xml. You can see that it starts with php warning for timezone: view-source:http://www.freshremix.ru/rss.xml
Technically it's their fault, although I can think of some hack 🤔

**Comment by happysurf** [comment]
You are right, also not pass the validate at https://validator.w3.org/feed/, but the strange thing is that in Netvibes works fine.

**Comment by Reeywhaar** [comment]
It works in Feedly too. I think it's a common thing in rss, and Feedly and Netvibes as commercial products try to accomodate to the reality :-)

**Comment by Reeywhaar** [comment]
Ha, they seem to be to fix the issue. Would be helpful to know is this a common thing in the wild. I could've try to parse from first index of `<?xml` header and assume that it may be not the first characters.

**Comment by Reeywhaar** [comment]
Applied loose parsing, for the case when rss starts not with xml header. I think this is the most I can do :-) https://github.com/Reeywhaar/want-my-rss/commit/42566ef5d285dfacb44e35e00ae9ec7893d48eb9
