### ISSUE TITLE
Copy link problem

### ISSUE THREAD

**Issue by happysurf** [Reeywhaar/want-my-rss#8]
If I click on RSS icon on this page for example, then appear in popup the title **"Recent Commits to want-my-rss:master"**, if I want to copy quickly the RSS link in context menu > **"Copy Link location"** the clipboard result is:
**moz-extension://2825c5ae-5048-4be4-a5b9-2edc35e303dc/show.html?url=https://github.com/Reeywhaar/want-my-rss/commits/master.atom**
but it should be:
**https://github.com/Reeywhaar/want-my-rss/commits/master.atom**
The problem is present on any RSS web page.

**Comment by Reeywhaar** [comment]
Understand, yes, should be fixed

**Comment by Reeywhaar** [comment]
Fixed in https://github.com/Reeywhaar/want-my-rss/commit/42566ef5d285dfacb44e35e00ae9ec7893d48eb9. Thank you!
