### ISSUE TITLE
XML files with RSS data

### ISSUE THREAD

**Issue by michele654** [Reeywhaar/want-my-rss#9]
Hi, thanks for the add-on, I really do want my rss... ;)

I would like to suggest atom files and XML files with RSS-style data, such as found in

https://www.moxa.com/RSS/Security_advisory.xml

and 

https://cert-portal.siemens.com/productcert/rss/advisories.atom

Thanks!

**Comment by Reeywhaar** [comment]
Hi!

I don't clearly understand the question. You mean that `Want My RSS` fails on said feeds? I see that https://www.moxa.com/RSS/Security_advisory.xml via moz-extension://{extension-id}/show.html?url=https://www.moxa.com/RSS/Security_advisory.xml works fine.

The second one is indeed doesn't work, though is valid Atom feed according to https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fcert-portal.siemens.com%2Fproductcert%2Frss%2Fadvisories.atom and should be fixed. Thanks for this one.

**Comment by Reeywhaar** [comment]
I fixed parsing of https://cert-portal.siemens.com/productcert/rss/advisories.atom in [0.9](https://github.com/Reeywhaar/want-my-rss/releases/tag/0.9), also I added protocol handler so feed can be viewed by typing [ext+rss:https://cert-portal.siemens.com/productcert/rss/advisories.atom](ext+rss:https://cert-portal.siemens.com/productcert/rss/advisories.atom)
